### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by aioue** [kroese/virtual-dsm#2]
Can you add any limitations into the README?

What can't it do?

**Comment by QuadNL** [comment]
Well Synology VMM is not possible and using a Synology account is not available too.

As far I can see only a single networking adapter is available to the docker container, but you can connect to the (multiple) physical adapters on the host via the bridge connection.

**Comment by aioue** [comment]
@kroese Can you bring those points out into the README, please? Will save you repeating yourself on future issues.
