### ISSUE TITLE
Is it possible to support GPU in the virtual dsm docker

### ISSUE THREAD

**Issue by jinlife** [kroese/virtual-dsm#234]
Is it possible to bypass /dev/dri to the docker like the jellyfin?
Also could you please add i915 driver in the virtual dsm? It seems there is no i915 driver.

**Comment by jinlife** [comment]
Thank you. I guess it can pass /dev/dri like the /dev/kvm, but there is no i915 driver at all.
Hope someone could solve it.

**Comment by fm365** [comment]
Hope virtual-dsm can support to passthrough GPU.

**Comment by Kissycat** [comment]
Make the container privileged, 
and exec to the container with cmd `docker exec -it dsm /bin/bash` to install graphic driver in debian container.
 `apt install xserver-xorg-video-intel`
Then replace [this](https://github.com/kroese/virtual-dsm/blob/6bd0cfd8249caf17cdb2db75a686f4ff59c66f79/run/run.sh#L76) line with `-display egl-headless,rendernode=/dev/dri/renderD128 -device virtio-vga,id=video0,max_outputs=1,bus=pcie.0,addr=0x1` , reboot, now your people album is working.

**Comment by Kissycat** [comment]
>  Can you test if it works?

Don't worry, both face recognition and video thumbnail are working with these arguments.

And now, I use it in a lxc container running on the openwrt, it also works well, and it solved ip issue(caused by macvlan isolation) when host is dhcp server.
