### ISSUE TITLE
issues about briage

### ISSUE THREAD

**Issue by a11505** [kroese/virtual-dsm#24]
Hello, thank you very much for providing such an excellent image. After deploying with Greenlink Cloud SSH, the address obtained by DSM is 20.20.20.21, and it is unable to communicate with the host and mount Samba devices on the host. I am considering that the issue may arise in the briage method. Can you obtain the address 172.17.0. * as the internal address of DSM to try to solve this problem? Thank you for reading.
您好，非常感谢您提供如此优秀的镜像，我使用绿联云ssh部署后，DSM获取到的地址是20.20.20.21，无法和宿主机通信，不能挂载宿主机samba设备。我考虑问题可能出现在briage这种方式上，能否获取172.17.0.*的地址作为DSM内部地址，以尝试解决这个问题，感谢阅读。

**Comment by a11505** [comment]
Thank you for your reply and providing such an excellent product. I have installed iputils and attempted to ping other devices and hosts, both of which can be pinged and mounted with Samba from other devices. However, I am unable to mount Samba from the host, resulting in data interoperability issues.

**Comment by a11505** [comment]
感谢回复以及提供如此优秀的产品，我安装了iputils并尝试ping其他设备和宿主机，都可以ping通，也可以挂载其他设备的samba，但是无法挂载宿主机的samba，导致数据无法互通。

**Comment by a11505** [comment]
I am installed on a UGREEN-NAS device, Like synology or QNAP. I hope to be able to mount the host's directory through vDSM for data sharing. Currently, vDSM can mount other devices on the local area network, but it cannot mount the host's samba.

**Comment by a11505** [comment]
> * ### How do I give the container a dedicated IP address?
>   By default the container uses bridge networking, and is reachable by the IP of the docker host.
>   If you want to give it a seperate IP address, create a MACVLAN network that matches your local subnet:
>   ```
>   $ docker network create -d macvlan \
>       --subnet=192.168.0.0/24 \
>       --gateway=192.168.0.1 \
>       --ip-range=192.168.0.100/28 \
>       -o parent=eth0 macvlan0
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   And change the network of the container to `macvlan0` in your run command:
>   ```
>    --network macvlan0 --ip=192.168.0.100
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This has the advantage that you don't need to do any portmapping anymore.

Thank You very much， it works!

**Comment by ziyou2** [comment]
> * ### 如何为容器提供专用IP地址？
>   默认情况下，容器使用桥接网络，并且可以通过docker主机的IP访问。
>   如果你想给它一个单独的IP地址，创建一个匹配你本地网的MACVLAN网络：
>   ```
>   $ docker network create -d macvlan \
>       --subnet=192.168.0.0/24 \
>       --gateway=192.168.0.1 \
>       --ip-range=192.168.0.100/28 \
>       -o parent=eth0 macvlan0
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   并在您的运行命令中将容器的网络更改为`macvlan0`：
>   ```
>    --network macvlan0 --ip=192.168.0.100
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   这样做的好处是您不再需要进行任何终端口投射。

If I have tailscale installed on my system with an intranet ip of 100.64.0.X/32, how do I use this command to connect via tailscale?

**Comment by ziyou2** [comment]
> 

version: '3.8'
services:
  vm:
    container_name: dsm
    image: kroese/virtual-dsm:latest
    restart: on-failure
    environment:
      DISK_SIZE: "32G"
      RAM_SIZE: "512M"
      CPU_CORES: "1"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./data:/storage
    networks:
      macvlan0:
        ipv4_address: 192.168.0.100

networks:
  macvlan0:
    external: true

I wrote it this way, docker-compose.yml, and although he ran it, it didn't work correctly, and I don't know how to write docker-compose.yml correctly to make it work

**Comment by ziyou2** [comment]
> @ziyou2 Can you tell what didn't work correctly? Because first you were talking about Tailscale so Im a bit confused.

Tailscale solution didn't work because I was using the headscale build
 I tried to “docker exec” dsm container and install headscale, but it didn't work

**Comment by ziyou2** [comment]
> You can login to vDSM, go to Package Center, and search for Tailscale and you will see the app, install it, and it will work fine.

Tailscale solution didn't work because I was using the headscale build

version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN                       
        ports:
            - 5000:5000
            - 5001:5001
        volumes:
            - ./data:/storage
        networks:
            vdsm:
                ipv4_address: 192.168.0.100

networks:
    vdsm:
        external: true


I use this docker-compose after editing it myself although it returns Creating dsm ... done, but it doesn't work properly

**Comment by honmaple** [comment]
@a11505 Hello, I see that you are using ugreen cloud and can normally use `macvlan`, but I find that ugreen cloud has not installed MACVLAN-related kernel modules
```
# lsmod | grep macvlan
# opkg info kmod-macvlan
Package: kmod-macvlan
Version: 5.10.186-1
Depends: kernel (= 5.10.186-1-64a64673aeb2b14d6f0f78fbfb7a1f84)
Status: unknown ok not-installed
Section: kernel
Architecture: x86_64
Size: 10967
Filename: kmod-macvlan_5.10.186-1_x86_64.ipk
Description: A kernel module which allows one to create virtual interfaces that
 map packets to or from specific MAC addresses to a particular interface
```
I try to install it manully, but got 
```
# opkg install kmod-macvlan
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Unknown package 'kmod-macvlan'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.186-1-64a64673aeb2b14d6f0f78fbfb7a1f84) for kmod-macvlan
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-macvlan found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-macvlan.
```

If  using docker to create an image without `kmod-macvlan`, I would get an error
```
docker: Error response from daemon: failed to create the macvlan port: operation not supported.
```
Could you please tell me how to solve it?

**Comment by a11505** [comment]
是的，绿联云没有该模块，且没有兼容的模块可以安装，极空间支持MACVLAN，我有多台设备，该解决方案在极空间有效，绿联云使用openwrt作为底层，有天生缺陷，可能无解。



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 4, 2023 00:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kroese/virtual-dsm] issues about briage (Issue #24)




 
@a11505 Hello, I see that you are using ugreen cloud and can normally use macvlan, but I find that ugreen cloud has not installed MACVLAN-related kernel modules
 # lsmod | grep macvlan # opkg info kmod-macvlan Package: kmod-macvlan Version: 5.10.186-1 Depends: kernel (= 5.10.186-1-64a64673aeb2b14d6f0f78fbfb7a1f84) Status: unknown ok not-installed Section: kernel Architecture: x86_64 Size: 10967 Filename: kmod-macvlan_5.10.186-1_x86_64.ipk Description: A kernel module which allows one to create virtual interfaces that  map packets to or from specific MAC addresses to a particular interface  
I try to install it manully, but got
 # opkg install kmod-macvlan Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest. Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest. Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest. Unknown package 'kmod-macvlan'. Collected errors:  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.186-1-64a64673aeb2b14d6f0f78fbfb7a1f84) for kmod-macvlan  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-macvlan found, but incompatible with the architectures configured  * opkg_install_cmd: Cannot install package kmod-macvlan.  
If  using docker to create an image without kmod-macvlan, I would get an error
 docker: Error response from daemon: failed to create the macvlan port: operation not supported.  
Could you please tell me how to solve it?
