### ISSUE TITLE
Failed to start Issue VDSM ready for intialization before boot-done

### ISSUE THREAD

**Issue by dieAls** [kroese/virtual-dsm#50]
hi kroese,

since three days I'm not able to  get the container started. maybe you have a hint for me? I have filtered out the "ok" messages from log:
[FAILED] Failed to start Load Kernel Modules.
See "systemctl status systemd-modules-load.service" for details.

[DEPEND] Dependency failed for Load Fan Modules in Kernel Project.
[DEPEND] Dependency failed for Adjust NIC sequence.
[DEPEND] Dependency failed for Load Kernel Modules in Kernel Project.
[DEPEND] Dependency failed for Prepare notification cache data.
[DEPEND] Dependency failed for Send dsmnotif...s of dsm and packages are ready.
[DEPEND] Dependency failed for Software Init Led for support led v2 models.

[DEPEND] Dependency failed for rebuild local user and group db.

[DEPEND] Dependency failed for Update all packages' feasibility config.

[FAILED] Failed to start synoindex check if ... any synoindex-related packages.
See "systemctl status synoindex-checkpackage.service" for details.

[DEPEND] Dependency failed for synoindexd.
[DEPEND] Dependency failed for synomkflvd.
[DEPEND] Dependency failed for synoindex scand.
[DEPEND] Dependency failed for synoindex mediad.
[DEPEND] Dependency failed for synoindex plugind.
[DEPEND] Dependency failed for synoindex workerd.
[DEPEND] Dependency failed for synoindex notifyd.
[DEPEND] Dependency failed for synomkthumbd.

[  OK  ] Started VPN Client.
[FAILED] Failed to start Issue VDSM ready for intialization before boot-done..

After the last "failed" message everthing will be stop :-(

My stack file:
![image](https://user-images.githubusercontent.com/63848382/232431923-0d5c6b2d-135c-436a-8dcf-a7c67e61be39.png)

Created files in persitant area:
![image](https://user-images.githubusercontent.com/63848382/232432195-1cdc18f4-0639-44f7-bace-fbe6e6e6c058.png)

Regards

**Comment by dieAls** [comment]
hi kroese. thank you for the quick response. until now i was not able to get the deployment finish. the errors are from initial setup. i have removed several times all files and started from scratch. 
i have added the comlete log. when are you are really, really bored maybe you can have a look inside ;-)


[dsm_logs.20230417.txt](https://github.com/kroese/virtual-dsm/files/11249487/dsm_logs.20230417.txt)

**Comment by dieAls** [comment]
My Setup: Proxmox => Docker (LXC) => DSM

KVM was not enabled for Docker at start. Check for solutions and done following:

Added entry for Docker LXC from host:
lxc.cgroup.devices.allow: c 10:232 rwm

Implement following steps on Docker LXC:
mknod /dev/kvm c 10 232
chmod 777 /dev/kvm
chown root:kvm /dev/kvm

After I was succesfully run KVM (kvm-ok) check and could start with DSM deployment.

Looks like it was not the complete solution  then :-)

**Comment by dieAls** [comment]
debian 11
will try to setup a vm with docker inside. that will take one, two days...

**Comment by Alan-dowayStudio** [comment]
Because the IP address is automatically assigned after the container restarts, it may not be 20.20.20.21, so it cannot be accessed. I fixed the IP address to 20.20.20.21 as soon as I installed it, the network type is bridge, and the connection is good so far. I waited for the author to develop a way to go through the network card and then reinstall it.

**Comment by dieAls** [comment]
As discussed i have build a VM with docker inside. Important was to switch CPU typ from default to "host" to enable KVM. Now DSM is working. Thank you very much for your support and for your good work.
